---
swagger: "2.0"
info:
  description: "A simple service to get cpuinfo as an example of using swagger -2.0\
    \ specification and codegen"
  version: "0.0.1"
  title: "cpuinfo"
  termsOfService: "http ://swagger.io/terms/"
  contact:
    name: "Cloudmesh REST Service Example "
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /cpu:
    get:
      description: "Returns cpu information"
      operationId: "cpu_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "CPU Info"
          schema:
            $ref: "#/definitions/cpu"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  CPU:
    type: "object"
    required:
    - "model"
    properties:
      model:
        type: "string"
