---
swagger: "2.0"
info:
  description: "A simple service to count words using Python and Spark"
  version: "0.0.1"
  title: "wordCount"
  termsOfService: "http ://swagger.io/terms/"
  contact:
    name: "PySpark word count Application"
host: "localhost:8080"
basePath: "/count"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /count:
    get:
      description: "Returns word count information"
      operationId: "count_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Word Count"
          schema:
            $ref: "#/definitions/words"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Words:
    type: "object"
    required:
    - "model"
    properties:
      model:
        type: "string"
